# spring配置文件，包含对数据库和日志级别的操作 author：张利红
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tree?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j
mybatis:
  # 让MyBatis映射指定Mybatis的Mapper文件
  mapper-locations: classpath:*/mapper/*.xml
  # 指定Mybatis的实体目录
  type-aliases-package: com.lonton.binaryTree.tree.pojo
server:
  port: 8080




