name: Junit

# on用来控制何时运行这个workflow
on:
  # 在push时触发这个事件workflow
  push:
    branches:
      - main
  # 允许你手动在Github网页上执行该workflow
  workflow_dispatch:

# 一个workflow可以由多个job组成，可以并行或者分离运行
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
    env:
      DB_DATABASE: ${{secrets.DB_DATABASE}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}

    steps:
        - uses: actions/checkout@v2
        # Start Mysql
        # https://ovirium.com/blog/how-to-make-mysql-work-in-your-github-actions/
        - name: Start Mysql
          run: |
              sudo systemctl start mysql
              mysql -e "use mysql; FLUSH PRIVILEGES; ALTER USER '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';" -uroot -proot
              mysql -e 'CREATE DATABASE tree;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

        # Set up JDK 1.8
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8



