#/**
# * CheckStyle.yml (工作流-GitHub Actions 自动托管代码,代码每次从本地 push到仓库时都会自动执行测试用例)
# *
# * @author 张利红
# */

# CheckStyle 的名称，会在 GitHub Action 页面上显示的名称
name: CheckStyle

# 代码只有在 push到 main 分支上才会此 workflow
on:
  push:
    branches: [ main ]
    # 仅在以下文件修改时才触发，减少每次细微修改 push 后在运行器上的周期浪费
  #  paths: [ '**.java', '.github/workflows/CheckStyle.yml', 'pom.xml' ]
  # 人工触发
  workflow_dispatch:

# 创建一个job
jobs:
  # 将此 job 的名称设定为 'build'
  build:
    # 执行在最新版本的 ubuntu runner 上
    runs-on: ubuntu-latest
    # 设定系统上的环境变量，包含连接数据库的设定 (例如 MySQL)
    # 较为私密的信息可以存放在 GitHub Action 的 secrets
    # 在 yml 文档中可以使用 ${{ secrets.SECRET_NAME }} 取得 secrets 中存放的值
    env:
      DB_DATABASE: ${{secrets.DB_DATABASE}}
      JAVA_HOME_8_X64: ${{secrets.JAVA_HOME_8_X64}}

    # 执行步骤
    steps:
      # 使用 actions/checkout@v3 这个官方的 action
      # 可以查看 workflow 的执行状况，并对 workflow 的虚拟环境进行指令操作（例如测试环境）
      - name: check out code
        uses: actions/checkout@v3

      # 设立时区
      - name: Set timezone to Shanghai
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Shanghai/etc/localtime

      # 缓存 Maven，以便在下次重启 workflow 时，加快 workflow 的执行速度
      - name: Cache local Maven repository
        id: cache-maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 缓存 JDK，以便在下次重启 workflow 时，加快 workflow 的执行速度
      - name: Cache JDK
        id: cache-jdk
        uses: actions/cache@v3
        with:
          path: ${{ env.JAVA_HOME_8_X64 }}
          key: ${{ runner.os }}-jdk-8
          restore-keys: ${{ runner.os }}-jdk-

        # 缓存  MySQL及 脚本，以便在下次重启 workflow 时，加快 workflow 的执行速度
      - name: Cache MySQL and SQL scripts
        id: cache-mysql-scripts
        uses: actions/cache@v2
        with:
          path: /usr/local/mysql/data
          key: ${{ runner.os }}-mysql-scripts-${{ hashFiles('**/*.sql') }}
          restore-keys: |
            ${{ runner.os }}-mysql-scripts-
            Linux-mysql-scripts-

      # 下载 Checkstyle
      - name: Download Checkstyle
        run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.42/checkstyle-8.42-all.jar

      # 运行 Checkstyle
      - name: Run Checkstyle
        run: java -jar checkstyle-8.42-all.jar -c ${GITHUB_WORKSPACE}/src/main/resources/checkstyle.xml -f xml -o checkstyle-report.xml ${GITHUB_WORKSPACE}/src/

      # 上传 Checkstyle 测试报告
      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-report
          path: checkstyle-report.xml
